# See https://docs.redoc.ly/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/openapi.yaml
  public: openapi/public.yaml
lint:
  extends:
    - recommended
  plugins:
    - './util/demo-plugin.js'
  decorators:
    demo/remove-internal-operations: error

referenceDocs:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"